# Generated by Django 3.1.4 on 2020-12-22 06:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_auto_20201221_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('post', models.TextField(max_length=2000)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 12, 22, 11, 30, 33, 678136))),
                ('category', models.CharField(max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.adduser')),
            ],
        ),
    ]
