# Generated by Django 3.1.4 on 2020-12-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adduser',
            options={'ordering': ['fname']},
        ),
        migrations.AddField(
            model_name='adduser',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
